dexnode_book_homepage:
    pattern:  /
    defaults: { _controller: DexnodeBookBundle:Default:index }

dexnode_book_show:
    path:   /book/{slug}
    defaults:  { _controller: DexnodeBookBundle:Default:show }